
--
-- LibSQL SQL Schema dump automatic generated by geni
--

CREATE TABLE sqlite_sequence(name,seq);
CREATE TABLE libsql_vector_meta_shadow ( name TEXT PRIMARY KEY, metadata BLOB ) WITHOUT ROWID;
CREATE TABLE schema_migrations (id VARCHAR(255) NOT NULL PRIMARY KEY);
CREATE TABLE documents (id integer PRIMARY KEY AUTOINCREMENT, content text NOT NULL, created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE document_chunks (id integer PRIMARY KEY AUTOINCREMENT, document_id integer NOT NULL REFERENCES documents (id) ON DELETE CASCADE, chunk text NOT NULL, metadata text, embedding f32_blob (1536) NOT NULL);
CREATE INDEX idx_document_chunks_document_id ON document_chunks (document_id);
CREATE TABLE idx_document_chunks_embedding_shadow (index_key  INTEGER , data BLOB, PRIMARY KEY (index_key));
CREATE INDEX idx_document_chunks_embedding_shadow_idx ON idx_document_chunks_embedding_shadow (index_key);
CREATE INDEX idx_document_chunks_embedding ON document_chunks (libsql_vector_idx (embedding));